Repository FossifyOrg/File-Manager, pull requests merged in 2025-05, with the labels that each got.

#172 docs: remove local pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#174 chore(l10n): update translations
  fastlane/metadata/android/iw-IL/short_description.txt
Labels: l10n

#187 ci: use fossifybot github app token
  .github/workflows/foss-release.yml
  .github/workflows/gplay-release.yml
  .github/workflows/image-minimizer.yml
  .github/workflows/no-response.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-commenter.yml
Labels: ci

#197 ci(dependabot): add jitpack registry for gradle
  .github/dependabot.yml
Labels: ci
